@startuml

hide circle
skinparam linetype ortho


' タスクマスタ
entity "tasks" {
  + id [PK]
  --
  # created_by [FK] /'作成者'/
  task       /'タスクタイトル'/
  comment    /'タスクを振るときのコメント'/
  is_done    /'完了フラグ（0で未完了、1で全員完了）：非正規化のため、task_assigned_users.is_doneを参照してもOK'/
  created_at /'タスク作成日'/
}


' タスクに追加されたユーザー
entity "task_assigned_users" {
  # task_id [FK]
  # user_id [FK]
  --
  is_done /'完了フラグ（0で未完了、1で完了）'/
  done_at /'タスク完了日'/
}

entity "users" {
  + id [PK]
  --
  name
  email
  password
}


' 繰り返し設定
' ーーーーーーーーーー
' 1. N時間おき　: numerical_value + unit_id (= hour)
' 2. N日おき　　: numerical_value + unit_id (= daily)
' 3. N週おき　　: numerical_value + unit_id (= weekly)
'   3-1. 曜日を指定しないパターン：optionなし（= タスク登録した曜日を参照）
'   3-2. 曜日を指定するパターン　：optionあり (= repeat_pattern_optionsを参照)
' 4. Nカ月おき　: numerical_value + unit_id (= monthly)
'   4-1. 日付を指定するパターン：
'   4-2. 末日を指定するパターン：optionあり (= repeat_pattern_optionsを参照)
' ーーーーーーーーーー
entity "repeat_setting" {
  # task_id [FK]  /'タスクID'/
  # unit_id [FK]  /'単位ID'/
  --
  numeric_value   /'数値'/
  option_types    /'オプションタイプ（0でオプションなし、1でoption_pattern、2でoption_numeric）'/
}


' 繰り返し単位
entity "repeat_units" {
  + id [PK]
  --
  + value /'hour, daily, weekly, monthy, yearlyの5種類'/
}


' 繰り返しオプション（パターン） -> 3-1, 4-2で有効
' ーーーーーーーーーー
' string_valueは、現時点で以下の通り。
'   1. sunday
'   2. monday
'   3. tuesday
'   4. wednesday
'   5. thursday
'   6. friday
'   7. saturday
'   8. last day of the month（月末日）
'   -> 縦持ちすることで、「毎週X曜日とY曜日」などの指定も可能
' ーーーーーーーーーー
entity "option_pattern" {
  # task_id [FK]
  --
  string_value 
}


' 繰り返しオプション（数値）-> 4-1で有効
entity "option_numeric" {
  # task_id [FK]
  --
  numeric_value
}


tasks ||-r-|{ task_assigned_users
tasks ||--|| repeat_setting
tasks }o-u-|| users
users ||--o{ task_assigned_users
repeat_setting ||-r-|| repeat_units
repeat_setting ||--o{ option_pattern
repeat_setting ||--o{ option_numeric

@enduml
