@startuml usecase

' ------------------------------ 設定
hide circle
hide method
skinparam linetype ortho
skinparam monochrome true
skinparam shadowing false


' ------------------------------ 管理者集約
rectangle 管理者集約 {
  class 管理者 {
    ID
    苗字
    名前
    メールアドレス
  }
  note left of 管理者
    ・メールアドレス：重複不可
  end note
}

' ------------------------------ チーム集約
rectangle チーム集約 {
  class チーム {
    ID
    チーム名
    ペアList<ペアID>
  }

  class ペア {
    ID
    ペア名
    参加者List<参加者ID>
  }

  note left of チーム
    ・チーム名：3文字以下の数値（重複不可）

    ・3名以上の参加者が必要

    ・人数変更時の挙動：
      ・チームが2名以下で管理者通知
        ・チームから抜けた参加者
        ・対象チーム
        ・対象チームの現在の参加者
  end note

  note left of ペア
    ・ペア名：1文字の英文字（重複OK）

    ・参加者数：2〜3名（1名や4名以上は不可）
      ・同じチーム内から組成する

    ・人数変更時の挙動：
      ・1名になった時点で他ペアへ自動合流（合流先からの許可不要）
        ・同じチーム内の最小人数ペアへ（人数が同じ場合ランダム）
        ・合流可能なペアがない場合管理者通知
          ・どの参加者がいなくなったのか
          ・どの参加者が合流先を探しているか
  end note
}

' ------------------------------ 参加者集約
rectangle 参加者集約 {
  class 参加者 {
    ID
    苗字
    名前
    メールアドレス
    在籍ステータス
  }

  class 在籍ステータス {
    ステータス
  }

  note left of 参加者
    ・メールアドレス：重複不可

    ・ステータスが在籍中のときだけチームやペアに所属可能

    ・復帰時の挙動：
      ・もっとも参加人数が少ないチーム・ペアへ合流
      ・4名以上になる場合自動的に2ペアに分割（ランダム）
  end note

  note left of 在籍ステータス
    ・「在籍中」「休会中」「退会済」のみ
  end note
}

' ------------------------------ 課題集約
rectangle 課題集約 {
  class 課題 {
    ID
    課題名
    課題本文
    課題カテゴリ
  }

  class 課題カテゴリ {
    課題カテゴリ
  }
}

' ------------------------------ 課題進捗集約
rectangle 課題進捗集約 {
  class 課題進捗 {
    参加者ID
    課題ID
    課題スタータス
  }

  class 課題ステータス {
    課題ステータス
  }

  note right of 課題進捗
    ・自分の課題のみステータス変更可能
    ・ステータスを「完了」に更新後、変更不可
  end note

  note right of 課題ステータス
    ・「未着手」「レビュー待ち」「完了」のみ
  end note
}


' ------------------------------ step3. relationship
' 集約内はインスタンス参照
チーム --* ペア
参加者 --* 在籍ステータス
課題 --* 課題カテゴリ
課題進捗 --* 課題ステータス

' 集約外はID参照
ペア --> 参加者
課題進捗 --> 参加者
課題進捗 --> 課題

@enduml